
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';
export const TOGGLE_MENU_ITEM = 'TOGGLE_MENU_ITEM';
export const FETCH_UNIVERSITIES_SUCCESS = 'FETCH_UNIVERSITIES_SUCCESS';
export const FETCH_UNIVERSITIES_FAIL = 'FETCH_UNIVERSITIES_FAIL';
export const FETCH_UNIVERSITIES_INIT = 'FETCH_UNIVERSITIES_INIT';
export const UNIVERSITIES_ADD_SUCCESS = 'UNIVERSITIES_ADD_SUCCESS';
export const UNIVERSITIES_ADD_FAIL = 'UNIVERSITIES_ADD_FAIL';
export const FETCH_UNIVERSITIESBYID_SUCCESS = 'FETCH_UNIVERSITIESBYID_SUCCESS';
export const FETCH_UNIVERSITIESBYID_FAIL = 'FETCH_UNIVERSITIESBYID_FAIL';
export const FETCH_UNIVERSITIESBYID_INIT = 'FETCH_UNIVERSITIESBYID_INIT';
export const UNIVERSITIES_UPDATE_SUCCESS = 'UNIVERSITIES_UPDATE_SUCCESS';
export const UNIVERSITIES_UPDATE_FAIL = 'UNIVERSITIES_UPDATE_FAIL';
export const UNIVERSITIES_DELETE_SUCCESS = 'UNIVERSITIES_DELETE_SUCCESS';
export const UNIVERSITIES_DELETE_FAIL = 'UNIVERSITIES_DELETE_FAIL';
export const AUDITPLAN_ADD_SUCCESS = "AUDITPLAN_ADD_SUCCESS";
export const AUDITPLAN_ADD_FAIL = "AUDITPLAN_ADD_FAIL";
export const FETCH_AUDITPLANS_INIT = "FETCH_AUDITPLANS_INIT";
export const FETCH_AUDITPLANS_SUCCESS = "FETCH_AUDITPLANS_SUCCESS";
export const FETCH_AUDITPLANS_FAIL = "FETCH_AUDITPLANS_FAIL";
export const FETCH_AUDITPLANBYID_SUCCESS = "FETCH_AUDITPLANBYID_SUCCESS";
export const FETCH_AUDITPLANBYID_FAIL = "FETCH_AUDITPLANBYID_FAIL";
export const FETCH_AUDITPLANBYID_INIT = "FETCH_AUDITPLANBYID_INIT";
export const FETCH_AUDITPLANNEDSTATUS_INIT ="FETCH_AUDITPLANNEDSTATUS_INIT";
export const FETCH_AUDITPLANNEDSTATUS_SUCCESS ="FETCH_AUDITPLANNEDSTATUS_SUCCESS";
export const FETCH_AUDITPLANNEDSTATUS_FAIL ="FETCH_AUDITPLANNEDSTATUS_FAIL";



