
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';
export const TOGGLE_MENU_ITEM = 'TOGGLE_MENU_ITEM';
export const FETCH_UNIVERSITIES_SUCCESS = 'FETCH_UNIVERSITIES_SUCCESS';
export const FETCH_UNIVERSITIES_FAIL = 'FETCH_UNIVERSITIES_FAIL';
export const FETCH_UNIVERSITIES_INIT = 'FETCH_UNIVERSITIES_INIT';


